from main import Therapist, Surgeon, Neurologist, InfectiousDiseaseSpecialist, Pediatrician, Traumatologist, Dentist, Cardiologist, Ophthalmologist, Gastroenterologist, Gynecologist

therapist1 = Therapist("Duysembayeva Mira Bolatkyzy", 15)
therapist2 = Therapist("Zhanashov Lukpan", 20)
surgeon1 = Surgeon("Nariman Ailana Baurzhankyzy", 18)
surgeon2 = Surgeon("Shamiyeva Nursaule Nurlankyzy", 22)
neurologist1 = Neurologist("Dossan Yernar", 16)
neurologist2 = Neurologist("Shamiyev Nurbol", 20)
gynecologist1 = Gynecologist("Agishan Medina", 12)
gynecologist2 = Gynecologist("Tekkesheva Kamila", 16)
traumatologist1 = Traumatologist("Rysqul Gani", 14)
traumatologist2 = Traumatologist("Nazymkhan ALibek", 19)
dentist1 = Dentist("Yerzhankyzy Akkumis", 17)
dentist2 = Dentist("Galymzhankyzy Ayaulym Qurmetkyzy", 21)
cardiologist1 = Cardiologist("Bekkaliyeva Ainara", 14)
cardiologist2 = Cardiologist("Kosbayev Adilet", 19)
ophthalmologist1 = Ophthalmologist("Talgatov Yerassyl", 15)
ophthalmologist2 = Ophthalmologist("Nazarabayeva Fariza", 21)
gastroenterologist1 = Gastroenterologist("Nurmukhambet Amina", 13)
gastroenterologist2 = Gastroenterologist("Orisbaev Madiyar", 18)
infectious1 = InfectiousDiseaseSpecialist("Sairanbayeva Lyazzat", 13)
infectious2 = InfectiousDiseaseSpecialist("Batyrgali Zhannur", 18)
pediatrician1 = Pediatrician("Tolepbargen Ogylan", 16)
pediatrician2 = Pediatrician("Kurmanbayev Zhandos", 20)
