from main import Therapist, Surgeon, Pediatrician, Traumatologist, Dentist, Cardiologist, Ophthalmologist

therapist1 = Therapist("Duysembayeva Mira Bolatkyzy", 15)
therapist2 = Therapist("Zhanashov Lukpan", 20)
surgeon1 = Surgeon("Nariman Ailana Baurzhankyzy", 18)
surgeon2 = Surgeon("Shamiyeva Nursaule Nurlankyzy", 22)
traumatologist1 = Traumatologist("Rysqul Gani", 14)
traumatologist2 = Traumatologist("Nazymkhan ALibek", 19)
dentist1 = Dentist("Yerzhankyzy Akkumis", 17)
dentist2 = Dentist("Galymzhankyzy Ayaulym Qurmetkyzy", 21)
cardiologist1 = Cardiologist("Bekkaliyeva Ainara", 14)
cardiologist2 = Cardiologist("Kosbayev Adilet", 19)
ophthalmologist1 = Ophthalmologist("Talgatov Yerassyl", 15)
ophthalmologist2 = Ophthalmologist("Nazarabayeva Fariza", 21)
pediatrician1 = Pediatrician("Tolepbargen Ogylan", 16)
pediatrician2 = Pediatrician("Kurmanbayev Zhandos", 20)
